__author__ = 'Meemaw'


print("Please insert numbers a and b for all integer combinations of a^b:")
lower = input("Insert a:")
upper = input("Insert b:")
set = set()
for i in range(lower,upper+1):
    for j in range(lower,upper+1):
        stevilo = i**j
        set.add(stevilo)
print("Number of distinct terms in the sequence generated by a^b:")
print(len(set))